name: Build and deploy gh-pages - Book 1

on:
  push:
    branches:
      - master
    paths:
      - 'book_src_1/*'
      - '.github/workflows/build-book1.yml'

jobs:
  build-and-deploy-book1:
    name: Build and deploy gh-pages
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : onejar99
      USER_EMAIL  : onejar99@gmail.com
      BOOK_DIR    : book_src_1
      OUTPUT_DIR  : book_src_1/_book

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2.3.1
      with:
        persist-credentials: false

    - name: Build 🔧
      run: |
        echo "pwd=[$(pwd)]"
        ls -al
        cd $BOOK_DIR
        docker run --rm -p 4000:4000 -v $(pwd):/gitbook onejar99/gitbook:light "gitbook init && gitbook install && gitbook build"

    # - name: Deploy 🚀
    #   uses: JamesIves/github-pages-deploy-action@3.5.7
    #   with:
    #     GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
    #     BRANCH: gh-pages
    #     FOLDER: book_src_1/_book

    - name: Deploy 🚀
      run: |
        echo "HOME=[$HOME]"
        echo "GITHUB_RUN_ID=[$GITHUB_RUN_ID]"
        echo "GITHUB_REPOSITORY=[$GITHUB_REPOSITORY]"
        echo "GITHUB_SHA=[$GITHUB_SHA]"
        echo "MY_SECRET=[$MY_SECRET]"
        echo "USER_NAME=[$USER_NAME]"
        echo "USER_EMAIL=[$USER_EMAIL]"
        echo "OUTPUT_DIR=[$OUTPUT_DIR]"
        echo "whoami=[$(whoami)]"
        echo "pwd=[$(pwd)]"
        GH_PAGES_FOLDER=$GITHUB_REPOSITORY_ghpages
        export GH_PAGES_FOLDER
        echo "GH_PAGES_FOLDER=[$GH_PAGES_FOLDER]"
        ls -al

        git clone -b gh-pages --single-branch https://$MY_SECRET@github.com/$GITHUB_REPOSITORY.git $GH_PAGES_FOLDER
        ls -al
        rm -rf $GH_PAGES_FOLDER/$BOOK_DIR
        cp -rf $OUTPUT_DIR $GH_PAGES_FOLDER/$BOOK_DIR
        cd $GH_PAGES_FOLDER
        ls -al

        git config --local user.name $USER_NAME
        git config --local user.email $USER_EMAIL
        git status
        git add --all
        git commit -m "Deploy to Github Pages 🥂 (from $GITHUB_SHA)"
        git push origin gh-pages -f
        echo Deploy gh-pages completed! 💪💯
